version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    colored-line-number: {}

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - goconst
    - gocritic
    - goheader
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - mnd

  settings:
    govet:
      shadow: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
        - hugeParam
    cyclop:
      max-complexity: 15
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - mnd
          - goconst
          - dupl
          - lll
      # Exclude known linters from partially hard-to-fix issues
      - path: cmd_.*\.go
        linters:
          - lll
      # Exclude shadow checking on the variable named err
      - text: 'shadow: declaration of "err"'
        linters:
          - govet

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - otter
